[project]
name = "devtools"
version = "0.1.0"
description = "Debugging tools."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "psutil>=7.0.0",
    "requests>=2.32.3",
    "rich>=13.9.4",
]
